Repository zabihhaqqani/Banana-Speak, pull requests merged in 2022-10, with the labels that each got.

#3 fixed the input field
  app.js
Labels: hacktoberfest

#6 code of conduct
  Code-of-conduct
Labels: documentation, hacktoberfest-accepted

#8 add icon to the button and cursor pointer
  index.html
  style.css
  translation.png
Labels: enhancement, hacktoberfest-accepted

#10 update button
  style.css
Labels: hacktoberfest-accepted

#12 Feature/icon and files
  .gitignore
  Code-of-conduct.md
  assets/img/minion.png
  assets/img/translation.png
  assets/script/app.js
  assets/style/style.css
  index.html
Labels: enhancement, hacktoberfest-accepted

#19 Added Speak Up Feature
  assets/img/speak.png
  assets/script/app.js
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, feature

#20 Dark mode feature
  assets/script/app.js
  assets/style/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, feature

#38 Styles - Added footer logos
  assets/style/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, feature

#41 Styles - Fixed textarea
  assets/style/style.css
  index.html
Labels: enhancement, hacktoberfest
